name: Build Xposed Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    # Cache Gradle dependencies
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-

    # Build the APK
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: XposedModule-APK
        path: app/build/outputs/apk/release/*.apk
